title: Evan Micheal Foster
description: Personal website of Evan Micheal Foster in Springfield, Illinois. Founder of IVA, doctoral student, writer, researcher, board treasurer, husband and father.
url: https://evanmichealfoster.com
baseurl: ""

markdown: kramdown
theme: null
permalink: pretty

plugins:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
